name: Release Geode Mod

on:
  workflow_dispatch:

jobs:
  release:
    name: Release mod
    runs-on: ubuntu-latest
    environment:
      name: release
      url: ${{ steps.release.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - uses: hiimjasmine00/release-geode-mod@main
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish mod
    runs-on: ubuntu-latest
    needs: ['release']
    environment:
      name: publish
      url: ${{ steps.publish.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - uses: hiimjasmine00/release-geode-mod/publish@main
        id: publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}